FROM python:3.6-slim

MAINTAINER Joir-dan Gumbs<jdagumbs@gmail.com>

# Are we debugging?
ARG DEBUG_ARG
# Arguments pertaining to Object Storage
ARG OS_AUTH_URI_ARG
ARG OS_PROJECT_ARG
ARG OS_PROJECT_ID_ARG
ARG OS_USER_ID_ARG
ARG OS_USERNAME_ARG
ARG OS_PASSWORD_ARG
ARG OS_DOMAIN_ID_ARG
ARG OS_DOMAIN_NAME_ARG
ARG OS_ROLE_ARG
ARG OS_CONTAINER_ARG
ARG OS_REGION_ARG
# MongoDB Specific Arguments
ARG MONGODB_HOST_ARG
ARG MONGODB_CA_CERT_ARG

# Take the arguments above, and turn them into ENV variables
ENV DEBUG $DEBUG_ARG
ENV OS_VERSION 3
ENV OS_AUTH_URI $OS_AUTH_URI_ARG
ENV OS_PROJECT $OS_PROJECT_ARG
ENV OS_PROJECT_ID $OS_PROJECT_ID_ARG
ENV OS_USER_ID $OS_USER_ID_ARG
ENV OS_USERNAME $OS_USERNAME_ARG
ENV OS_PASSWORD $OS_PASSWORD_ARG
ENV OS_DOMAIN_ID $OS_DOMAIN_ID_ARG
ENV OS_DOMAIN_NAME $OS_DOMAIN_NAME_ARG
ENV OS_ROLE $OS_ROLE_ARG
ENV OS_CONTAINER $OS_CONTAINER_ARG
ENV OS_REGION OS_REGION_ARG

ENV MONGODB_HOST $MONGODB_HOST_ARG
ENV MONGODB_CA_CERT $ MONGODB_CA_CERT_ARG

ENV SC2READER_CACHE_DIR "/cache/sc2reader"
ENV SC2READER_CACHE_MAX_SIZE 100

EXPOSE 9999

COPY . /app
WORKDIR /app
RUN  pip install -r requirements.txt

CMD ["python",  app.py]
