#!/bin/bash

DEBUG=0 OS_PROJECT="<OBJECT_STORAGE_PROJECT>" OS_PROJECT_ID="<OBJECT_STORAGE_ID>" OS_REGION="<OBJECT_STORAGE_REGION>" OS_USER_ID="<OBJECT_STORAGE_USER_ID>" \
OS_USERNAME="<OBJECT_STORAGE_USERNAME>" OS_PASSWORD="<OBJECT_STORAGE_PASSWORD>" OS_DOMAIN_ID="<OBJECT_STORAGE_DOMAIN_ID>" OS_DOMAIN_NAME="<OBJECT_STORAGE_DOMAINNAME>" \
OS_VERSION=3 OS_ROLE="<OBJECT_STORAGE_ROLE>" OS_CONTAINER="<OBJECT_STORAGE_CONTAINER>" MONGODB_HOST="<MONGODB_HOST_URL>" MONGODB_CA_CERT="<MONGODB_CERT_PATH>" python3.6 app.py
